<?xml version="1.0"?>
<robot xmlns:xacro = "http://www.ros.rog/wiki/xacro">

        <xacro:property name = "base_length" value = "1"/>
        
        
        <xacro:macro name = "wheel_link" params = 'prefix'>
            <link name = "${prefix}_wheel_link">
                <visual>
                    <geometry>
                        <cylinder radius="0.1" length = "0.05"/>
                    </geometry>
                    <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
                    <material name="somethingshit"></material>
                </visual>
                </link>

        </xacro:macro>


        <link name="base_link">
                <visual>
                    <geometry>
                        <box size="${base_length} 0.4 0.2" />
                    </geometry>

                    <origin xyz="0 0 0.1" rpy="0 0 0" />
                    <material name="green"></material>
                </visual>
            </link>

            <link name="caster_wheel">
                <visual>
                    <geometry>
                        <sphere radius = "0.05"/>
                        <material name="caster_wheel"/>
                    </geometry>
                </visual>
            </link>


            <xacro:wheel_link prefix = 'left'></xacro:wheel_link>
            <xacro:wheel_link prefix = 'right'></xacro:wheel_link>



            <joint name="base_right_wheel_joint" type="continuous">
                <origin xyz = "${-base_length / 4} -0.225 0" rpy = "${pi} 0 0"/>
                <parent link="base_link"/>
                <child link="right_wheel_link"/>
                <axis xyz="0 1 0"/>
            </joint>


            <joint name="base_left_wheel_joint" type="continuous">
                <origin xyz = "${-base_length / 4} 0.225 0" rpy = "${pi} 0 0"/>
                <parent link="base_link"/>
                <child link="left_wheel_link"/>
                <axis xyz="0 1 0"/>
            </joint>

            <joint name = "base_caster_joint" type = "fixed">
                <origin xyz = "${base_length / 4} 0 -0.075" rpy = "0 0 0"/>
                <parent link = "base_link"/>
                <child link = "caster_wheel"/>

            </joint>


</robot>